package info.androidhive.materialdesign.activity;

import java.util.HashMap;

/**
 * Created by ASUS on 5/5/2016.
 */
public class Hashkorerakha {
    public final HashMap<String,String> hmap= new HashMap<String, String>();
    public Hashkorerakha() {
        hmap.put("আমি", "ami");
        hmap.put("আলো", "alo");
        hmap.put("বাড়ি", "bari");
        hmap.put("বাসা", "basha");
        hmap.put("বিজয়", "bijoy");
        hmap.put("বিকাল", "bikal");
        hmap.put("বন্ধু", "bondhu");
        hmap.put("ছেলে", "chele");
        hmap.put("দুপুর", "dupur");
        hmap.put("গান", "gaan");
        hmap.put("ঘর", "ghor");
        hmap.put("ঘুম", "ghum");
        hmap.put("গল্প", "golpo");
        hmap.put("হাসি", "hashi");
        hmap.put("হতাশ", "hotash");
        hmap.put("জীবন", "jibon");
        hmap.put("খাবার", "khabar");
        hmap.put("খাই", "khai");
        hmap.put("খারাপ", "kharap");
        hmap.put("খাটো", "khato");
        hmap.put("কবিতা", "kobita");
        hmap.put("মাঝে", "majhe");
        hmap.put("মেয়ে", "meye");
        hmap.put("মোটা", "mota");
        hmap.put("রাত", "rat");
        hmap.put("সাধারণ", "sadharon");
        hmap.put("সাহস", "sahosh");
        hmap.put("শেষ", "sesh");
        hmap.put("শুরু", "shuru");
        hmap.put("সকাল", "sokal");
        hmap.put("ভাল", "valo");
        hmap.put("ভাত", "vat");
        hmap.put("খাই", "khai");
        hmap.put("আকাশ","akash");
        hmap.put("আমরা","amra");
        hmap.put("বাংলা","bangla");
        hmap.put("বাতাস","batash");
        hmap.put("বই","boi");
        hmap.put("বলা","bola");
        hmap.put("বস","bosho");
        hmap.put("বসুন","boshun");
        hmap.put("চোখ","chokh");
        hmap.put("ডাল","daal");
        hmap.put("দাঁড়ান","daran");
        hmap.put("দাড়াও","darao");
        hmap.put("দেশ","desh");
        hmap.put("দিয়ে","diye");
        hmap.put("দূরত্ব","durotto");
        hmap.put("গাড়ি","gaari");
        hmap.put("গাছ","gach");
        hmap.put("ঘড়ি","ghori");
        hmap.put("হাল্কা","haalka");
        hmap.put("হাত","haat");
        hmap.put("হাঁটা","haata");
        hmap.put("যাই","jai");
        hmap.put("যাও","jao");
        hmap.put("খাও","khao");
        hmap.put("কি","ki");
        hmap.put("কখন","kokhon");
        hmap.put("কলম","kolom");
        hmap.put("করে","kore");
        hmap.put("করি","kori");
        hmap.put("করো","koro");
        hmap.put("কথা","kotha");
        hmap.put("কোথায়","kothay");
        hmap.put("কঠিন","kothin");
        hmap.put("লিখা","likha");
        hmap.put("মাছ","mach");
        hmap.put("মাংস","mangsho");
        hmap.put("মাথা","matha");
        hmap.put("না","na");
        hmap.put("পা","pa");
        hmap.put("পানি","pani");
        hmap.put("পড়া","pora");
        hmap.put("পড়ি","pori");
        hmap.put("রাস্তা","raasta");
        hmap.put("রক্ত","rokto");
        hmap.put("রঙ","rong");
        hmap.put("সে","shey");
        hmap.put("সোজা","shoja");
        hmap.put("শোনা","shona");
        hmap.put("সবজি","sobji");
        hmap.put("সময়","somoy");
        hmap.put("সঠিক","sothik");
        hmap.put("তারা","taara");
        hmap.put("টাকা","taka");
        hmap.put("তোমরা","tomra");
        hmap.put("তুমি","tumi");
        hmap.put("ভারি","vaari");
        hmap.put("ভুল","vul");
        hmap.put("আমার","amar");
        hmap.put("আপনি","apni");
        hmap.put("বাংলাদেশ","bangladesh");
        hmap.put("বাংলাদেশে","bangladeshe");
        hmap.put("বাসা","basha");
        hmap.put("বাসায়","bashay");
        hmap.put("বিজ্ঞান","biggan");
        hmap.put("ক্লাস","klass");
        hmap.put("কম্পিউটার","computer");
        hmap.put("ঢাকা","dhaka");
        hmap.put("ঢাকায়","dhakay");
        hmap.put("এ","e");
        hmap.put("এবং","ebong");
        hmap.put("ফারিবা","fariba");
        hmap.put("খাব","khabo");
        hmap.put("খাবো","khabo");
        hmap.put("খন্দকার","khondokar");
        hmap.put("মামুন","mamun");
        hmap.put("মিরপুর","mirpur");
        hmap.put("নাম","nam");
        hmap.put("নাজমুল","nazmul");
        hmap.put("নমুনা","nomuna");
        hmap.put("ও","o");
        hmap.put("প্রকৌশল","prokoushol");
        hmap.put("প্রকৌশলী","prokousholi");
        hmap.put("থাকি","thaki");

        hmap.put("আছেন", "achen");
        hmap.put("আছি", "achi");
        hmap.put("আছো", "acho");
        hmap.put("আমাদের", "amader");
        hmap.put("অর্ণব", "arnab");
        hmap.put("এই", "ei");
        hmap.put("এখানে", "ekhane");
        hmap.put("এখন", "ekhon");
        hmap.put("একটা", "ekta");
        hmap.put("এটা", "eta");
        hmap.put("ইচ্ছে", "icche");
        hmap.put("কাগজ", "kagoj");
        hmap.put("কাজ", "kaj");
        hmap.put("কেমন", "kemon");
        hmap.put("কখনও", "kokhono");
        hmap.put("কখনো", "kokhono");
        hmap.put("নববর্ষ", "noboborsho");
        hmap.put("ঐ", "oi");
        hmap.put("ওটা", "ota");
        hmap.put("সেখানে", "sekhane");
        hmap.put("শুভ", "shuvo");
        hmap.put("টা", "ta");
        hmap.put("তাদের", "tader");
        hmap.put("তারা", "tara");
        hmap.put("তখন", "tokhon");
        hmap.put("তোমাদের", "tomader");
        /*hmap.put("","");*/
    }
    public String get(String t)
    {
        return hmap.get(t);
    }
}
